### ISSUE TITLE
unable to build from docker file - Step 11/52 : ADD --chown=axway:axway $INSTALL_KIT installkit.zip

### ISSUE THREAD

**Issue by sanvaibhav** [Axway/docker-cft#2]
ADD failed: Get https://delivery.server.com/Transfer_CFT_3.4_Install_linux-x86-64_BN12392000.zip: dial tcp: lookup delivery.server.com on 192.168.65.1:53: no such host

**Comment by ftovo-axway** [comment]
You should follow the instructions on the section [How to build the Docker image](https://github.com/Axway/docker-cft#how-to-build-the-docker-image) from the README.
